### ISSUE TITLE
`lift` rules are confusing and/or broken

### ISSUE THREAD

**Issue by jdidion** [milkschen/leviosam2#20]
I am trying to run the full workflow. I end up with nearly half my reads in the `unliftable` BAM, and most of them do not fall within one of the un-liftable regions specified in the `-R` file.

When I set the `-A` and `-q` parameters to `0`, then most of the un-liftable reads become liftable.

The documentation makes it sounds like `-A` and `-q` only determine whether a read goes to `committed` or `deferred` - they should not by themselves send any reads to the `unliftable` file. If this is not the case then this should be made more clear in the documentation, otherwise it seems there is a bug.

**Comment by jdidion** [comment]
I opened this bug after looking at the intermediate outputs of the full workflow while it was running. Now that it's finished the `uniftable` file only has a small number of reads. Some of these are un-liftable due to being in un-liftable regions, and those appear in the `final` file as unmapped as I'd expect. However, there are some other reads in the un-liftable file that appear in the `final` file with alignment coordinates, indicating that they were re-mapped.

It would really help to have a more detailed explanation of how the full workflow works. It doesn't seem to match up exactly with what it says in the pre-print. Thanks

**Comment by milkschen** [comment]
The logic used in the current workflow:

* The `*-unliftable.bam` file: deferred + unliftable reads using the **source** coordinate system
* The `*-deferred.bam` file: deferred reads using the **target** coordinate system

The logic is at: https://github.com/milkschen/leviosam2/blob/075575bc75309cd650926818125fe7e046c75426/src/leviosam.cpp#L261 

I design this logic because the deferred reads in the source coordinate system could still be helpful. And it's costly to query such information from the original (unlifted) BAM. 

The chain file can be converted into a BED file (my [chaintools](https://github.com/milkschen/chaintools) supports the operation), which can then be fed to `bedtools intersect` for the extraction of strictly unliftable alignments. I agree that this can be confusing. Would it help if I add a (optional) flag to only report strictly unliftable alignments in `*-unliftable.bam`?

**Comment by jdidion** [comment]
Ok, this makes much more sense now. Maybe you could add these details to the README or a comment in the leviosam2.sh script?

Thanks!

**Comment by milkschen** [comment]
That's a great suggestion. Thank you!

 I updated the README (of the workflow) at https://github.com/milkschen/leviosam2/commit/412cb480c0e950371ec5a2842628c95f3b070cab
